import React, {useContext} from 'react';

import {AppContext} from "../../App"; 


function ImageClue () {


    const appContext = useContext(AppContext);
    const {levelData} = appContext;

//
//<img id="imageClueImage" src="https://ipfs.io/ipfs/QmYiTM4uSYryNq3KhvLc7WKnnHH7STe69WfyXcPtZDMP9T/00000000000000000000000000001100.png" alt="Image"/>


    return (

        <div className="image-clue">
         <img id="imageClueImage" src={levelData.imageURL} alt="Image"/>
            <div className = "imageClue-tagline">
            generated by MidJourney
            </div>
        </div>
        
        );
}

export default ImageClue;