import React, {useContext} from 'react';

import {AppContext} from "../../App"; 




function ImageClue () {


    const appContext = useContext(AppContext);
    const {levelData, setSelectedDreamDisplayIndex, selectedDreamDisplayIndex} = appContext;

//
//<img id="imageClueImage" src="https://ipfs.io/ipfs/QmYiTM4uSYryNq3KhvLc7WKnnHH7STe69WfyXcPtZDMP9T/00000000000000000000000000001100.png" alt="Image"/>


    const selectDot1 = () => {
        setSelectedDreamDisplayIndex(0);
    }
    const selectDot2 = () => {
        setSelectedDreamDisplayIndex(1);
    }
    const selectDot3 = () => {
        setSelectedDreamDisplayIndex(2);
    }
    const selectDot4 = () => {
        setSelectedDreamDisplayIndex(3);
    }



    let imgClueClassName = "imageClueImage";

    imgClueClassName += (selectedDreamDisplayIndex+1);



    return (

        <div>

            <div className="imageClueContainer">
                <img className={imgClueClassName} src={levelData.imageURL} alt="Image"/>
            </div>

            <div class="imageClueImage-dots">
                <span className={selectedDreamDisplayIndex == 0 ? "imageClueImage-dot active" : "imageClueImage-dot"} onClick={selectDot1}></span>
                <span className={selectedDreamDisplayIndex == 1 ? "imageClueImage-dot active" : "imageClueImage-dot"} onClick={selectDot2}></span>
                <span className={selectedDreamDisplayIndex == 2 ? "imageClueImage-dot active" : "imageClueImage-dot"} onClick={selectDot3}></span>
                <span className={selectedDreamDisplayIndex == 3 ? "imageClueImage-dot active" : "imageClueImage-dot"} onClick={selectDot4}></span>
            </div>

            <div className = "imageClue-tagline">
            generated by MidJourney
            </div>
        </div>
        
        );
}

export default ImageClue;